name: Auto Create Pull Request

on:
  push:
    branches:
      - '*'

permissions:
  pull-requests: write
  
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: create pull request
        run: gh pr create -B master -f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}