name: Auto Create Pull Request

on:
  push:
    branches-ignore:
      - "master"

permissions:
  pull-requests: write
  
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: create pull request
        run: gh pr create --fill-first
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}