name: Auto Create Pull Request

on:
  create:
    branches:
      - '*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          branch: ${{ github.event.ref }}
          title: 'Auto-created Pull Request'
          body: 'This pull request was automatically created by GitHub Actions.'
